day12/djangodemo/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]


day12/djangodemo/mysite/ninjas/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:dev_id>/', views.details, name='details'),
]

day12/djangodemo/mysite/ninjas/models.py
from django.db import models

# Create your models here.


class Developer(models.Model):
    devName = models.CharField(max_length=80)
    experience = models.IntegerField(default=0)
    country = models.CharField(max_length=20)

    def __str__(self):
        return self.devName


class Skill(models.Model):
    skillName = models.CharField(max_length=50)
    level = models.CharField(max_length=100,default="Beginner")
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)

    def __str__(self):
        return self.skillName

day12/djangodemo/mysite/ninjas/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.

from .models import Developer


def index(request):
    dev_list = Developer.objects.all()
    context = {
        'dev_list': dev_list
    }
    return render(request, 'ninjas/index.html', context)

def details(request, dev_id):
    dev = get_object_or_404(Developer, pk=dev_id)
    return render(request, 'ninjas/details.html', {'dev':dev})

day12/djangodemo/mysite/templates/ninjas/details.html
<html>
<body>
    <h1>{{ dev.devName }}</h1>
    <table border="1">
        <tr>
            <th>Name</th>
            <th>Level</th>
        </tr>

        {% for lang in dev.skill_set.all %}
            <tr>
                <td>{{ lang.skillName }}</td>
                <td>{{ lang.level }}</td>
            </tr>
        {% endfor %}

    </table>
</body>
</html>

day12/djangodemo/mysite/templates/ninjas/index.html
<html>
<body>

    {% if dev_list %}
        <table border="1">
            <tr>
                <th>Name</th>
                <th>Experience</th>
                <th>Country</th>
            </tr>

            {% for dev in dev_list %}
            <tr>
                <td><a href="{% url 'ninja:details' dev.id %}">{{dev.devName}}</a></td>
                <td>{{ dev.experience }}</td>
                <td>{{ dev.country }}</td>
            </tr>
            {% endfor %}

        </table>
    {% else %}
        <h1>No Data in Developers</h1>    
    {% endif %}

</body>
</html>