day14/django1/django1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('ninjas.urls')),
    path('admin/', admin.site.urls),
]

day14/django1/ninjas/urls.py
from django.urls import path

from . import views

app_name = 'ninjas'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:dev_id>/', views.DetailsView.as_view(), name='details'),
    path('<int:dev_id>/level/', views.level, name='level'),

]

day14/django1/ninjas/models.py

from django.db import models

# Create your models here.


class Developer(models.Model):
    devName = models.CharField(max_length=80)
    experience = models.IntegerField(default=0)
    country = models.CharField(max_length=20)

    def __str__(self):
        return self.devName


class Skill(models.Model):
    skillName = models.CharField(max_length=50)
    level = models.IntegerField()
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)

    def __str__(self):
        return self.skillName

day14/django1/ninjas/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView

from .models import Developer, Skill

class IndexView(ListView):
    template_name = 'ninjas/index.html'
    context_object_name = 'devs'

    def get_queryset(self):
        return Developer.objects.all()

class DetailsView(ListView):
    model = Developer
    template_name = 'ninjas/details.html'
    context_object_name = 'dev'
    def get_queryset(self):
        return Developer.objects.filter(pk=self.kwargs['dev_id']).first()

def level(request, dev_id):
    dev = get_object_or_404(Developer, pk=dev_id)
    try:
        dev_skill = dev.skill_set.get(pk=request.POST['skill'])  
    except(KeyError, Skill.DoesNotExist):
        return render(request, 'ninjas/details.html',{
            'dev' : dev,
            'error_message' : 'No such skill found'
        })
    else:
        dev_skill.level += 1
        dev_skill.save()
        return  HttpResponseRedirect(reverse('ninjas:details', args=(dev.id,)))          
    

day14/django1/templates/ninjas/details.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'ninjas/style.css' %}">
<h1>{{dev.devName}}</h1>
<form action="{% url 'ninjas:level' dev.id %}" method="post">
{% csrf_token %}
<table border="1">
    <tr><th>Name</th>
    <th>Level</th>
    <th>UpGrade</th></tr>
    {% for lang in dev.skill_set.all %}
        <tr>
            <td>{{lang.skillName}}</td>
            <td>{{lang.level}}</td>
            <td><input type="radio" name="skill" id="skill{{forloop.counter}}" value="{{lang.id}}"></td>
        </tr>
    {% endfor %}
</table>
<input type="submit" value="Level Up">
</form>

day14/django1/templates/ninjas/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'ninjas/style.css' %}">
{% if devs %}
    <table border="1">
        <tr>
            <th>Name</th>
            <th>Experience</th>
            <th>Country</th>
        </tr>

        {% for dev in devs %}
        <tr>
            <td><a href="{% url 'ninjas:details' dev.id %}">{{dev.devName}}</a></td>
            <td>{{dev.experience}}</td>
            <td>{{dev.country}}</td>
        </tr>
        {% endfor %}

    </table>
{% else %}
    <h1>No Data in Developers</h1>
{% endif %}